---
root: true

plugins:
  - jest
  - babel

env:
  node: true
  jest: true
  browser: true

parser: "@babel/eslint-parser"

extends:
  - "airbnb-base"
  - "plugin:jest/recommended"

rules:
  no-console: 0
  import/extensions: 0
  indent: 0
  consistent-return: 0
  no-use-before-define: 0